const products=[
{id:"watcher-01",name:"THE WATCHER TEE 01",code:"RA-001",price:3490,cat:"T-SHIRTS",collection:"THE WATCHER",sizes:["S","M","L","XL","XXL"],desc:"A study in awareness, intelligence and unseen power. The central octopus is built as a visual emblem rather than decoration.",story:"The Watcher observes before it moves. The octopus becomes a metaphor for intelligence without noise — adaptable, patient and difficult to read.",material:"250 GSM French terry cotton · bio-washed",fit:"Oversized",art:"octopus1.png"},
{id:"depth-02",name:"DEPTH TEE 02",code:"RA-002",price:3290,cat:"T-SHIRTS",collection:"DEPTH",sizes:["S","M","L","XL"],desc:"A restrained graphic about what exists beneath the visible surface.",story:"Depth is not darkness. It is the space where attention becomes understanding.",material:"240 GSM combed cotton",fit:"Relaxed",art:"octopus2.png"},
{id:"signal-01",name:"SIGNAL OVERSHIRT 01",code:"RA-003",price:6990,cat:"OUTERWEAR",collection:"UNKNOWN TERRITORY",sizes:["S","M","L","XL","XXL"],desc:"A modular overshirt carrying technical marks and hidden utility details.",story:"Designed as a bridge between garment and object.",material:"Cotton nylon canvas",fit:"Boxy",art:"signal.png"},
{id:"void-01",name:"VOID OBJECT TEE 01",code:"RA-004",price:3690,cat:"T-SHIRTS",collection:"UNKNOWN TERRITORY",sizes:["S","M","L","XL"],desc:"A monochrome composition built around negative space, proportion and restraint.",story:"The absence is part of the graphic.",material:"260 GSM heavyweight cotton",fit:"Oversized",art:"void.png"},
{id:"trace-03",name:"TRACE TEE 03",code:"RA-005",price:3490,cat:"T-SHIRTS",collection:"DEPTH",sizes:["S","M","L","XL","XXL"],desc:"A fragmented line system tracing movement through space.",story:"A record of movement made static.",material:"250 GSM cotton",fit:"Oversized",art:"trace.svg"},
{id:"field-01",name:"FIELD TROUSER 01",code:"RA-006",price:7490,cat:"BOTTOMS",collection:"UNKNOWN TERRITORY",sizes:["S","M","L","XL"],desc:"A considered everyday trouser with architectural pocket placement.",story:"Function becomes visible through proportion.",material:"Cotton ripstop",fit:"Wide straight",art:"field.png"},
{id:"watcher-02",name:"THE WATCHER LONGSLEEVE",code:"RA-007",price:4590,cat:"T-SHIRTS",collection:"THE WATCHER",sizes:["S","M","L","XL"],desc:"An extended silhouette carrying the Watcher system across front, back and sleeve.",story:"A second chapter in the Watcher visual language.",material:"280 GSM cotton jersey",fit:"Oversized",art:"octopus1.png"},
{id:"archive-cap",name:"ARCHIVE CAP 01",code:"RA-008",price:2490,cat:"ACCESSORIES",collection:"THE WATCHER",sizes:["ONE"],desc:"Six-panel cotton cap with restrained atelier marking.",story:"A small carrier for the larger system.",material:"Washed cotton",fit:"Adjustable",art:"cap.png"}
];
let cart=JSON.parse(localStorage.getItem("rytheCart")||"[]"), selectedSize=null;
const app=document.getElementById("app"), count=document.getElementById("cartCount");
function money(n){return "₹"+n.toLocaleString("en-IN")}
function img(p,cls=""){return `<img class="${cls}" src="assets/${p.art}" alt="${p.name}" loading="lazy">`}
function save(){localStorage.setItem("rytheCart",JSON.stringify(cart));updateCart()}
function updateCart(){count.textContent=cart.reduce((s,i)=>s+i.qty,0);renderCart()}
function toast(t){const e=document.getElementById("toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),1800)}
function productCard(p){return `<article class="product-card"><a href="#/product/${p.id}"><div class="product-image">${img(p)}<span class="quick btn btn-dark">VIEW PIECE</span></div><div class="product-meta"><div><span>${p.name}</span><small>${p.code} · ${p.collection}</small></div><span class="price">${money(p.price)}</span></div></a></article>`}
function home(){const featured=products.slice(0,4);app.innerHTML=`
<section class="hero"><div class="hero-copy"><div class="eyebrow">RYTHE ATELIER / COLLECTION 001</div><h1>DESIGNED<br><em>WITH</em><br>INTENT.</h1><p>Contemporary garments shaped by story, function and visual identity.</p><div class="actions"><a class="btn btn-light" href="#/collections/the-watcher">EXPLORE COLLECTION</a><a class="btn btn-light" href="#/about">DISCOVER RYTHE</a></div></div><div class="hero-art">${img(products[0])}</div></section>
<section class="statement"><h2>STORY<br>OVER NOISE.</h2><p>Every piece begins with an idea. The garment is where that idea becomes physical. RYTHE ATELIER builds a consistent visual language instead of chasing the moment.</p></section>
<section class="section"><div class="section-head"><h2>Selected Pieces</h2><a class="mono" href="#/shop">VIEW ALL →</a></div><div class="product-grid">${featured.map(productCard).join("")}</div></section>
<section class="story"><div class="story-media">${img(products[0])}</div><div class="story-copy"><div class="eyebrow">COLLECTION 001 / THE WATCHER</div><h2>THE<br>WATCHER</h2><p>Intelligence. Patience. Unseen power. The octopus becomes a symbol for the ability to observe, adapt and move without unnecessary noise.</p><div class="actions"><a class="btn btn-light" href="#/collections/the-watcher">READ THE STORY</a></div></div></section>
<section class="manifesto"><p>RYTHE ATELIER / DESIGN PRINCIPLES</p><h2>IDENTITY OVER TRENDS.<span>DESIGN OVER DECORATION.</span></h2><a class="btn btn-dark" href="#/about">OUR APPROACH</a></section>
<section class="newsletter"><div><h3>ENTER THE ATELIER.</h3><p>New releases, studio notes and selected stories.</p></div><form class="signup" onsubmit="subscribe(event)"><input type="email" required placeholder="YOUR EMAIL"><button>JOIN →</button></form></section>`}
function shop(){app.innerHTML=`<div class="page"><div class="eyebrow">RYTHE ATELIER / SHOP</div><h1 class="page-title">THE<br>COLLECTION.</h1><div class="filters" id="filters"><button class="filter active" data-cat="ALL">ALL</button>${["T-SHIRTS","OUTERWEAR","BOTTOMS","ACCESSORIES"].map(x=>`<button class="filter" data-cat="${x}">${x}</button>`).join("")}</div><div class="product-grid" id="shopGrid">${products.map(productCard).join("")}</div></div>`;document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");const c=b.dataset.cat;document.getElementById("shopGrid").innerHTML=products.filter(p=>c==="ALL"||p.cat===c).map(productCard).join("")})}
function collection(slug){const isW=slug==="the-watcher", name=isW?"THE WATCHER":"UNKNOWN TERRITORY", ps=products.filter(p=>p.collection===name|| (isW&&p.collection==="THE WATCHER"));app.innerHTML=`<div class="collection-hero"><div class="eyebrow">COLLECTION 001 / RYTHE ATELIER</div><h1>${name.replace(" ","<br>")}</h1><p>${isW?"An exploration of intelligence, awareness and unseen power. The octopus is treated as a symbolic system — not a motif.":"A study of function, movement and the spaces between visible and hidden design."}</p></div><div class="page"><div class="section-head"><h2>${ps.length} Pieces</h2><span class="mono">STORY · FORM · FUNCTION</span></div><div class="product-grid">${ps.map(productCard).join("")}</div></div>`}
function productPage(id){const p=products.find(x=>x.id===id)||products[0];selectedSize=null;app.innerHTML=`<div class="product-page"><div class="gallery">${[p.art,p.art,p.art,p.art].map(a=>`<img src="assets/${a}" alt="${p.name}">`).join("")}</div><div class="product-info"><div class="eyebrow">${p.code} / ${p.collection}</div><h1>${p.name}</h1><div class="price">${money(p.price)}</div><p class="description">${p.desc}</p><div class="mono">SELECT SIZE</div><div class="size-grid">${p.sizes.map(s=>`<button onclick="selectSize(this,'${s}')">${s}</button>`).join("")}</div><button class="btn btn-dark full" onclick="addToCart('${p.id}')">ADD TO BAG</button><div class="detail-list"><details open><summary>THE STORY</summary><p>${p.story}</p></details><details><summary>MATERIAL</summary><p>${p.material}</p></details><details><summary>FIT</summary><p>${p.fit}</p></details><details><summary>SHIPPING</summary><p>Dispatch within 2–4 business days. Tracking provided after dispatch.</p></details><details><summary>CARE</summary><p>Cold wash inside out. Do not bleach. Air dry. Iron inside out on low heat.</p></details></div></div></div>`}
function selectSize(el,s){selectedSize=s;document.querySelectorAll(".size-grid button").forEach(x=>x.classList.remove("selected"));el.classList.add("selected")}
function addToCart(id){const p=products.find(x=>x.id===id);if(!selectedSize)selectedSize=p.sizes[0];const key=id+"-"+selectedSize, existing=cart.find(x=>x.key===key);if(existing)existing.qty++;else cart.push({key,id,size:selectedSize,qty:1});save();toast("ADDED TO BAG");openCart()}
function updateQty(key,d){const x=cart.find(i=>i.key===key);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(i=>i.key!==key);save()}
function renderCart(){const box=document.getElementById("cartItems"), sub=document.getElementById("cartSubtotal");if(!box)return;if(!cart.length){box.innerHTML='<div style="padding:40px 24px;color:#766e76">YOUR BAG IS EMPTY.<br><br><a href="#/shop" class="btn btn-dark">EXPLORE COLLECTION</a></div>';sub.textContent="₹0";return}let total=0;box.innerHTML=cart.map(i=>{const p=products.find(x=>x.id===i.id);total+=p.price*i.qty;return `<div class="cart-line">${img(p)}<div><h4>${p.name}</h4><small>SIZE ${i.size} · ${money(p.price)}</small><div class="qty"><button onclick="updateQty('${i.key}',-1)">−</button><span>${i.qty}</span><button onclick="updateQty('${i.key}',1)">+</button></div></div><button class="remove" onclick="removeItem('${i.key}')">REMOVE</button></div>`}).join("");sub.textContent=money(total)}
function removeItem(k){cart=cart.filter(i=>i.key!==k);save()}
function openCart(){document.getElementById("cartDrawer").classList.add("open")}
function closeCart(){document.getElementById("cartDrawer").classList.remove("open")}
function about(){app.innerHTML=`<div class="page"><div class="eyebrow">THE ATELIER</div><h1 class="page-title">WE DESIGN<br>WITH INTENT.</h1><div class="statement" style="padding:80px 0"><h2>NOT FOR<br>THE MOMENT.</h2><p>RYTHE ATELIER is a contemporary fashion label built around intentional design, visual storytelling, experimentation and timeless identity. We believe clothing can carry ideas without becoming loud. Every graphic, silhouette, material and detail belongs to one larger visual language.</p></div><section class="manifesto" style="padding:100px 0"><p>OUR PRINCIPLES</p><h2>STORY OVER NOISE.<span>IDENTITY OVER TRENDS.</span><span>QUALITY OVER QUANTITY.</span></h2></section></div>`}
function lookbook(){app.innerHTML=`<div class="page"><div class="eyebrow">VISUAL ARCHIVE / 001</div><h1 class="page-title">THE<br>LOOKBOOK.</h1><div class="lookbook-grid">${products.concat(products.slice(0,3)).map(p=>`<a href="#/product/${p.id}">${img(p)}</a>`).join("")}</div></div>`}
function journal(){const posts=[["THE WATCHER","Why the octopus became a symbol of intelligence, patience and adaptation.","STORY"],["DESIGNING A VISUAL LANGUAGE","Consistency is not repetition. It is recognition.","DESIGN"],["THE WEIGHT OF A GARMENT","Why GSM, hand feel and silhouette change perception.","MATERIAL"]];app.innerHTML=`<div class="page"><div class="eyebrow">RYTHE ATELIER / JOURNAL</div><h1 class="page-title">STUDIO<br>NOTES.</h1><div class="article-grid">${posts.map((p,i)=>`<article class="article-card"><img src="assets/${products[i].art}" alt=""><small class="mono">${p[2]}</small><h3>${p[0]}</h3><p>${p[1]}</p></article>`).join("")}</div></div>`}
function checkout(){let total=cart.reduce((s,i)=>s+products.find(p=>p.id===i.id).price*i.qty,0);app.innerHTML=`<div class="checkout"><div class="eyebrow">RYTHE ATELIER / CHECKOUT</div><h1 class="page-title">COMPLETE<br>ORDER.</h1><div class="checkout-grid"><form class="form" onsubmit="placeOrder(event)"><label>EMAIL</label><input type="email" required><label>FULL NAME</label><input required><label>ADDRESS</label><input required><label>CITY</label><input required><label>PINCODE</label><input required pattern="[0-9]{6}"><label>PHONE</label><input required><button class="btn btn-dark full">PLACE DEMO ORDER · ${money(total)}</button></form><div class="summary-box"><div class="mono">ORDER SUMMARY</div>${cart.map(i=>{const p=products.find(x=>x.id===i.id);return `<div class="summary-row"><span>${p.name} × ${i.qty}</span><span>${money(p.price*i.qty)}</span></div>`}).join("")}<hr><div class="summary-row"><strong>TOTAL</strong><strong>${money(total)}</strong></div><p style="color:#766e76;font-size:11px">This front-end build uses a demo checkout. Connect Stripe/payment provider before accepting live payments.</p></div></div></div>`}
function placeOrder(e){e.preventDefault();cart=[];save();location.hash="/order-confirmation"}
function confirmation(){app.innerHTML=`<div class="page" style="min-height:60vh;display:flex;flex-direction:column;justify-content:center;align-items:flex-start"><div class="eyebrow">ORDER CONFIRMED</div><h1 class="page-title">THANK<br>YOU.</h1><p>Your demo order has been received. In production, this step should be connected to your payment and order-management backend.</p><a class="btn btn-dark" href="#/shop">CONTINUE SHOPPING</a></div>`}
function simple(title,body){app.innerHTML=`<div class="page"><div class="eyebrow">RYTHE ATELIER</div><h1 class="page-title">${title}</h1><div style="max-width:700px;font-size:17px;color:#575058">${body}</div></div>`}
function subscribe(e){e.preventDefault();e.target.reset();toast("YOU'RE IN — WELCOME TO THE ATELIER")}
function route(){let [path,param]=location.hash.replace(/^#\/?/,"").split("/");if(!path)home();else if(path==="shop")shop();else if(path==="collections")collection(param||"the-watcher");else if(path==="product")productPage(param);else if(path==="lookbook")lookbook();else if(path==="journal")journal();else if(path==="about")about();else if(path==="checkout")checkout();else if(path==="order-confirmation")confirmation();else if(path==="contact")simple("CONTACT","For collaborations, press, wholesale and general enquiries, contact the studio. Replace this text with your production email and contact form.");else if(path==="size-guide")simple("SIZE GUIDE","Use the product-specific fit notes and measurements here. Replace this section with RYTHE’s final measurement chart.");else if(path==="faq")simple("FAQ","Shipping, returns, sizing and product questions can be organized here.");else if(path==="shipping")simple("SHIPPING","Orders dispatch within 2–4 business days. Add your final shipping policy before launch.");else if(path==="returns")simple("RETURNS","Add the final RYTHE ATELIER return policy before launch.");else if(path==="privacy")simple("PRIVACY","Add the final privacy policy before launch.");else if(path==="terms")simple("TERMS","Add the final terms of service before launch.");else if(path==="account")simple("ACCOUNT","Account authentication is the next production integration. This build keeps the front-end route ready.");else home();window.scrollTo(0,0)}
document.getElementById("cartBtn").onclick=openCart;document.getElementById("closeCart").onclick=closeCart;document.getElementById("menuBtn").onclick=()=>document.getElementById("mobileMenu").classList.add("open");document.getElementById("closeMenu").onclick=()=>document.getElementById("mobileMenu").classList.remove("open");document.querySelectorAll(".mobile-menu a").forEach(a=>a.onclick=()=>document.getElementById("mobileMenu").classList.remove("open"));document.getElementById("searchBtn").onclick=()=>{document.getElementById("searchOverlay").classList.remove("hidden");document.getElementById("globalSearch").focus()};document.getElementById("closeSearch").onclick=()=>document.getElementById("searchOverlay").classList.add("hidden");document.getElementById("globalSearch").oninput=e=>{const q=e.target.value.toLowerCase();document.getElementById("searchResults").innerHTML=q?products.filter(p=>(p.name+p.collection+p.cat).toLowerCase().includes(q)).map(p=>`<a class="search-result" href="#/product/${p.id}"><span>${p.name}</span><span>${money(p.price)}</span></a>`).join("")||"<p>No results.</p>":""};document.getElementById("closeAnnouncement").onclick=()=>document.getElementById("announcement").remove();window.addEventListener("hashchange",route);updateCart();route();
